
spring:
  profiles:
    active: "prod"
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  application:
   name: department
  datasource:
    url: 'jdbc:h2:mem:depdb'
  h2:
   console:
    enabled: true
  #    url : jdbc:mysql://localhost:3306/test
  #    username: root
  #    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
   service-url:
    defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
build :
  version : "1.0"
author:
  name: "nadhem bel Hadj"
  email: "nadhemb@yahoo.com"